In [11]:
# Import libraries

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split

import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.utils import to_categorical

In [12]:
# Import dataset

names = ['ID','UserID','first_name','last_name','email','gender','City','Country', 'Age', 'Profession','Adventure','Architecture', 'Beach', 'Clothing', 'Food', 'Nature','MainCategory']
dataset = pd.read_csv("F:/Masters/Semester 3/Thesis/x17170885/Dataset/Cleaning/dataset-final.csv", delimiter=",",names=names)
dataset.drop(dataset.columns[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], axis=1, inplace=True)
dataset = dataset.iloc[1:]

X = dataset.iloc[:, :-1].values  
y = dataset.iloc[:, 6].values

y = to_categorical(y, num_classes=None)

In [13]:
dataset

    Adventure Architecture Beach Clothing Food Nature MainCategory
1           1            1     2        0    3      2            4
2           3            3     0        1    1      2            1
3           3            2     0        0    2      3            5
4           3            5     0        0    0      2            1
5           3            3     0        1    1      2            1
6           2            2     1        1    2      2            5
7           0            3     1        2    1      3            1
8           1            5     0        3    1      0            1
9           2            3     3        0    2      0            2
10          3            3     0        2    1      1            0
11          3            5     0        0    2      0            1
12          1            3     1        1    0      4            5
13          1            4     1        0    3      1            1
14          2            2     0        4    0      2            3
15          3            3     1        0    0      3            1
16          2            5     2        1    0      0            1
17          2            4     1        1    0      2            1
18          2            1     2        1    0      4            5
19          2            5     1        1    0      1            1
20          3            3     0        0    2      2            1
21          3            1     1        0    1      4            5
22          1            5     0        3    1      0            1
23          1            2     1        3    0      3            3
24          1            3     0        4    0      2            3
25          1            3     1        1    2      2            1
26          3            2     0        1    2      2            0
27          3            3     1        1    1      1            1
28          4            1     0        0    1      4            5
29          2            5     0        2    0      1            1
30          0            5     0        2    2      1            1
..        ...          ...   ...      ...  ...    ...          ...
262         2            0     4        0    2      2            2
263         4            3     0        1    0      2            0
264         0            5     1        0    1      3            1
265         4            2     1        1    0      2            0
266         1            1     2        0    6      0            4
267         1            3     1        3    2      0            3
268         3            4     0        1    1      1            1
269         1            0     2        5    2      0            3
270         3            3     0        1    1      2            0
271         4            3     1        1    0      1            0
272         1            0     2        4    1      2            3
273         2            2     0        1    3      2            4
274         0            2     0        0    5      3            4
275         2            2     0        1    4      1            4
276         2            0     3        5    0      0            3
277         0            1     1        2    1      5            5
278         2            6     0        1    1      0            1
279         1            3     4        0    0      2            2
280         3            0     5        0    1      1            2
281         2            2     0        0    1      5            5
282         5            2     0        0    1      2            0
283         3            1     0        1    0      5            5
284         3            2     1        2    1      1            0
285         4            6     0        0    0      0            1
286         1            5     1        1    0      2            1
287         3            2     2        0    2      1            0
288         5            1     2        0    1      1            0
289         2            3     1        2    2      0            1
290         2            0     0        3    1      4            3
291         1            1     4        0    1      3            2

[291 rows x 7 columns]

In [14]:
# Splitting dataset

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 4)  

# reshape input to be [samples, time steps, features]
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1],1))
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1],1))

y_train = np.reshape(y_train, (y_train.shape[0], y_train.shape[1],1))
y_test = np.reshape(y_test, (y_test.shape[0], y_test.shape[1],1))

X_test.shape

(59, 6, 1)

In [15]:
classifier = keras.Sequential()

classifier.add(Dense(units=256, kernel_initializer='uniform', activation='relu'))
classifier.add(Dropout(rate=0.4))
classifier.add(Dense(units=128, kernel_initializer='uniform', activation='relu'))
classifier.add(Dropout(rate=0.3))
classifier.add(Dense(units=1, kernel_initializer='uniform', activation='softmax'))


classifier.summary()

ValueError: This model has not yet been built. Build the model first by calling build() or calling fit() with some data. Or specify input_shape or batch_input_shape in the first layer for automatic build.

In [16]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [17]:
classifier.fit(X_train, y_train, epochs=40, batch_size=128, validation_data=(X_test,y_test), verbose=1)

Train on 232 samples, validate on 59 samples
Epoch 1/40
232/232 [==============================] - 1s 3ms/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 2/40
232/232 [==============================] - 0s 99us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 3/40
232/232 [==============================] - 0s 82us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 4/40
232/232 [==============================] - 0s 95us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 5/40
232/232 [==============================] - 0s 90us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 6/40
232/232 [==============================] - 0s 95us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 7/40
232/232 [==============================] - 0s 82us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 8/40
232/232 [==============================] - 0s 95us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 9/40
232/232 [==============================] - 0s 90us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 10/40
232/232 [==============================] - 0s 95us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 11/40
232/232 [==============================] - 0s 86us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 12/40
232/232 [==============================] - 0s 99us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 13/40
232/232 [==============================] - 0s 103us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 14/40
232/232 [==============================] - 0s 90us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 15/40
232/232 [==============================] - 0s 103us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 16/40
232/232 [==============================] - 0s 86us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 17/40
232/232 [==============================] - 0s 90us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 18/40
232/232 [==============================] - 0s 95us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 19/40
232/232 [==============================] - 0s 99us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 20/40
232/232 [==============================] - 0s 82us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 21/40
232/232 [==============================] - 0s 95us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 22/40
232/232 [==============================] - 0s 90us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 23/40
232/232 [==============================] - 0s 82us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 24/40
232/232 [==============================] - 0s 82us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 25/40
232/232 [==============================] - 0s 82us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 26/40
232/232 [==============================] - 0s 90us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 27/40
232/232 [==============================] - 0s 73us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 28/40
232/232 [==============================] - 0s 90us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 29/40
232/232 [==============================] - 0s 77us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 30/40
232/232 [==============================] - 0s 90us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 31/40
232/232 [==============================] - 0s 86us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 32/40
232/232 [==============================] - 0s 86us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 33/40
232/232 [==============================] - 0s 86us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 34/40
232/232 [==============================] - 0s 86us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 35/40
232/232 [==============================] - 0s 99us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 36/40
232/232 [==============================] - 0s 82us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 37/40
232/232 [==============================] - 0s 82us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 38/40
232/232 [==============================] - 0s 77us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 39/40
232/232 [==============================] - 0s 90us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667
Epoch 40/40
232/232 [==============================] - 0s 77us/step - loss: 13.2853 - acc: 0.1667 - val_loss: 13.2853 - val_acc: 0.1667