In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("F:/Masters/Semester 3/thesis/x17170885/Dataset/Cleaning/lstm-dataset.csv", delimiter=",")

In [3]:
df

               L1            L2            L3            L4            L5
0    Architecture  Architecture        Nature        Nature      Clothing
1    Architecture        Nature        Nature      Clothing     Adventure
2          Nature        Nature      Clothing     Adventure     Adventure
3          Nature      Clothing     Adventure     Adventure          Food
4        Clothing     Adventure     Adventure          Food          Food
5       Adventure     Adventure          Food          Food        Nature
6       Adventure          Food          Food        Nature  Architecture
7            Food          Food        Nature  Architecture     Adventure
8            Food        Nature  Architecture     Adventure     Adventure
9          Nature  Architecture     Adventure     Adventure        Nature
10   Architecture     Adventure     Adventure        Nature        Nature
11      Adventure     Adventure        Nature        Nature        Nature
12      Adventure        Nature        Nature        Nature          Food
13         Nature        Nature        Nature          Food  Architecture
14         Nature        Nature          Food  Architecture          Food
15         Nature          Food  Architecture          Food          Food
16           Food  Architecture          Food          Food  Architecture
17   Architecture          Food          Food  Architecture        Nature
18           Food          Food  Architecture        Nature  Architecture
19           Food  Architecture        Nature  Architecture        Nature
20   Architecture        Nature  Architecture        Nature          Food
21         Nature  Architecture        Nature          Food        Nature
22   Architecture        Nature          Food        Nature          Food
23         Nature          Food        Nature          Food        Nature
24           Food        Nature          Food        Nature        Nature
25         Nature          Food        Nature        Nature  Architecture
26           Food        Nature        Nature  Architecture  Architecture
27         Nature        Nature  Architecture  Architecture  Architecture
28         Nature  Architecture  Architecture  Architecture  Architecture
29   Architecture  Architecture  Architecture  Architecture  Architecture
..            ...           ...           ...           ...           ...
84           Food        Nature  Architecture     Adventure     Adventure
85         Nature  Architecture     Adventure     Adventure        Nature
86   Architecture     Adventure     Adventure        Nature        Nature
87      Adventure     Adventure        Nature        Nature        Nature
88      Adventure        Nature        Nature        Nature          Food
89         Nature        Nature        Nature          Food  Architecture
90         Nature        Nature          Food  Architecture          Food
91         Nature          Food  Architecture          Food          Food
92           Food  Architecture          Food          Food  Architecture
93   Architecture          Food          Food  Architecture        Nature
94           Food          Food  Architecture        Nature  Architecture
95           Food  Architecture        Nature  Architecture        Nature
96   Architecture        Nature  Architecture        Nature          Food
97         Nature  Architecture        Nature          Food        Nature
98   Architecture        Nature          Food        Nature          Food
99         Nature          Food        Nature          Food        Nature
100          Food        Nature          Food        Nature        Nature
101        Nature          Food        Nature        Nature  Architecture
102          Food        Nature        Nature  Architecture  Architecture
103        Nature        Nature  Architecture  Architecture  Architecture
104        Nature  Architecture  Architecture  Architecture  Architecture
105  Architecture  Architecture  Architecture  Architecture  Architecture
106  Architecture  Architecture  Architecture  Architecture  Architecture
107  Architecture  Architecture  Architecture  Architecture  Architecture
108  Architecture  Architecture  Architecture  Architecture  Architecture
109  Architecture  Architecture  Architecture  Architecture  Architecture
110  Architecture  Architecture  Architecture  Architecture  Architecture
111  Architecture  Architecture  Architecture  Architecture  Architecture
112  Architecture  Architecture  Architecture  Architecture  Architecture
113  Architecture  Architecture  Architecture  Architecture  Architecture

[114 rows x 5 columns]

In [4]:
from sklearn import preprocessing

In [5]:
l = preprocessing.LabelEncoder()
df['L1'] = l.fit_transform(df['L1'])

l = preprocessing.LabelEncoder()
df['L2'] = l.fit_transform(df['L2'])

l = preprocessing.LabelEncoder()
df['L3'] = l.fit_transform(df['L3'])

l = preprocessing.LabelEncoder()
df['L4'] = l.fit_transform(df['L4'])

l = preprocessing.LabelEncoder()
df['L5'] = l.fit_transform(df['L5'])

In [6]:
df

     L1  L2  L3  L4  L5
0     1   1   4   4   2
1     1   4   4   2   0
2     4   4   2   0   0
3     4   2   0   0   3
4     2   0   0   3   3
5     0   0   3   3   4
6     0   3   3   4   1
7     3   3   4   1   0
8     3   4   1   0   0
9     4   1   0   0   4
10    1   0   0   4   4
11    0   0   4   4   4
12    0   4   4   4   3
13    4   4   4   3   1
14    4   4   3   1   3
15    4   3   1   3   3
16    3   1   3   3   1
17    1   3   3   1   4
18    3   3   1   4   1
19    3   1   4   1   4
20    1   4   1   4   3
21    4   1   4   3   4
22    1   4   3   4   3
23    4   3   4   3   4
24    3   4   3   4   4
25    4   3   4   4   1
26    3   4   4   1   1
27    4   4   1   1   1
28    4   1   1   1   1
29    1   1   1   1   1
..   ..  ..  ..  ..  ..
84    3   4   1   0   0
85    4   1   0   0   4
86    1   0   0   4   4
87    0   0   4   4   4
88    0   4   4   4   3
89    4   4   4   3   1
90    4   4   3   1   3
91    4   3   1   3   3
92    3   1   3   3   1
93    1   3   3   1   4
94    3   3   1   4   1
95    3   1   4   1   4
96    1   4   1   4   3
97    4   1   4   3   4
98    1   4   3   4   3
99    4   3   4   3   4
100   3   4   3   4   4
101   4   3   4   4   1
102   3   4   4   1   1
103   4   4   1   1   1
104   4   1   1   1   1
105   1   1   1   1   1
106   1   1   1   1   1
107   1   1   1   1   1
108   1   1   1   1   1
109   1   1   1   1   1
110   1   1   1   1   1
111   1   1   1   1   1
112   1   1   1   1   1
113   1   1   1   1   1

[114 rows x 5 columns]

In [7]:
df['L1'] = df['L1']/10
df['L2'] = df['L2']/10
df['L3'] = df['L3']/10
df['L4'] = df['L4']/10
df['L5'] = df['L5']/10

In [9]:
df.to_csv("F:/Masters/Semester 3/thesis/x17170885/Dataset/Cleaning/lstm-dataset-final.csv", sep=',')